### ISSUE TITLE
Make network requests and other IO async to avoid UI stutter

### ISSUE THREAD

**Issue by arades79** [arades79/hyperdome#18]
polling the server for new messages makes dragging the window noticeably laggy. Networking should always be async in the first place.

**Comment by stevenpitts** [comment]
Making the network requests async will only change things if the UI is also async, which isn't supported well with PyQT5. 
Options:
1. Make networking and UI both async. UI code will be messier.
2. Make networking async and have UI run in a separate thread, which will make networking faster when there are multiple IO operations happening at once, which will rarely happen ever.
3. Keep networking blocking, have UI run in separate thread. 

Option 3 is cleaner than option 1, and almost as fast as option 2, but it'd be multithreaded. PyQT5 has issues with running in any thread other than the main, so that's gross. 

I'm working on option 1 now, to see how complicated it'd be.

**Comment by stevenpitts** [comment]
New plan:
Have a second thread to do the networking, and have it dispatch callbacks to the main UI thread that deal with updating UI elements.

**Comment by arades79** [comment]
Using pyqt's QThread may also solve this problem, some examples already exist within the codebase, and they allow for UI feedback from thread events.
