### ISSUE TITLE
Should language support be removed?

### ISSUE THREAD

**Issue by stevenpitts** [arades79/hyperdome#23]
Currently there's support for different languages, but at Hyperdome's currents stage, it will not be feasible to continue supporting different languages for new features. I propose we remove different language support for the time being, and then readd it in the future if Hyperdome becomes popular enough to justify it.
Thoughts?

**Comment by arades79** [comment]
Translations are not directly our responsibility. Most languages in Onionshare are community maintained.
Currently it seems irrelevant to support the feature as much of the text displayed is not even final, and using text resources can slow down development in this volatile phase. 
However, the infrastructure in place to support multiple languages is robust, and even if only English is maintained by us, using the infrastructure in place for managing locales will make the process of translation orders of magnitude easier for future translators.
Probably the pragmatic thing to do is to ensure the develop branch is using named text resources before being promoted into a more stable branch.

So yes, we should not support any other language besides English, the text resource infrastructure that facilitates translations should be maintained so that community members willing can add translations.

**Comment by arades79** [comment]
Upon further inspection, it does seem like local changing can be done in a cleaner way. However current translations are likely still useful, since most are for button labels or hint text.
